language: android
jdk: oraclejdk8
branches:
  only:
  - master
  - develop
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - extra-android-m2repository
  - extra-google-m2repository
  - android-28
  - sys-img-x86-android-28
  - sys-img-armeabi-v7a-android-17
licenses:
  - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"


script: ./gradlew
