language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.1.1
  - extra-android-m2repository
  - extra-google-m2repository
  - android-28
#  - sys-img-x86-android-28
#  - sys-img-armeabi-v7a-android-17
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'


script: ./gradlew
