language: android
jdk: oraclejdk8
branches:
  only:
  - master
  - develop
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - extra-android-m2repository
  - extra-google-m2repository
  - android-28
  - sys-img-x86-android-28
licenses:
  - 'android-sdk-license-.+'

before_install:
  before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  # Install the rest of tools (e.g., avdmanager).
  - sdkmanager tools
  # Install the system image.
  - sdkmanager "system-images;android-19;default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  - echo no | avdmanager create avd --force -n test -k "system-images;android-19;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &
install: ./gradlew clean assemble --stacktrace

before_script:
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &



script: ./gradlew check connectedCheck --stacktrace
